[package]
name = "merkle-tree"
version = "0.3.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
hash = {path = "../hash"}
serde = "1.0"
serde_derive = "1.0"